# Generated by Django 4.2.7 on 2023-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDescGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='folder_name',
            field=models.CharField(default='temp_default', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
