# Generated by Django 4.2.7 on 2023-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDescGen', '0004_userupload_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='csv_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
