# Generated by Django 4.2.7 on 2023-12-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AIDescGen', '0005_userupload_csv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userupload',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userupload',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userupload',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userupload',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
